"""
Video Frame Synchronization Tool

Usage:
    This script synchronizes frames across multiple camera videos based on known 
    synchronization points. It reads frame information from CSV files generated by 
    the frame extraction script and matches frames across cameras using timestamps.

    The script:
    1. Reads CSV files containing frame numbers and timestamps for each camera
    2. Uses known synchronization points (sync_points) to calculate time offsets
    3. Matches frames across cameras by finding the closest timestamp match
    4. Outputs a synchronized frame mapping CSV file
    5. Visualizes dropped frames in a bar chart (one rectangle per camera with red lines for dropped frames)
    6. Outputs a CSV file listing all dropped frame numbers for each camera

    Input CSV format (from 1_get_frame_info.py):
        frame_number,cap_msec
        0,0
        1,10
        2,26
        ...

    Output CSV format:
        Camera1,Camera2,Camera3,Camera4,Camera5,Camera6
        0,0,0,0,0,0
        1,1,1,1,1,1
        ...

    Example:
        Modify the following variables in the __main__ section:
        - dir: Directory containing CSV files (e.g., Camera1_0_results.csv)
        - video_name: Video name suffix (e.g., '0' for files ending with '_0_results.csv')
        - sync_points: Dictionary mapping camera numbers to sync frame numbers
          Format: {camera_num: sync_frame_num}
          Example: {1: 315, 2: 298, 3: 287, 4: 292, 5: 297, 6: 289}
        - base_camera: Reference camera number (default: 1)

    How sync_points work:
        If Camera1's frame 315, Camera2's frame 298, Camera3's frame 287, etc. 
        are synchronized (represent the same moment in time), specify them in 
        sync_points. The script will calculate time offsets and match frames 
        accordingly.

    Output files:
        - synchronized_frames_with_offset_{video_name}.csv: Synchronized frame mapping
        - dropped_frames_visualization_{video_name}.png: Visualization of dropped frames
        - dropped_frames_{video_name}.csv: List of dropped frame numbers for each camera

    Requirements:
        - numpy
        - matplotlib (for visualization)
        - tqdm (for progress bars)
        - CSV files generated by 1_get_frame_info.py
"""

import os
import csv
import math
import cv2
import concurrent.futures
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection
from tqdm import tqdm
import argparse
from pathlib import Path


def read_csv_file(file_path):
    """Read CSV file and return frame numbers and timestamps as NumPy arrays"""
    print(f"Reading file: {file_path}")
    frame_numbers = []
    timestamps = []
    try:
        with open(file_path, 'r', newline='') as f:
            reader = csv.reader(f)
            header = next(reader)  # Skip header row
            for row in reader:
                frame_numbers.append(int(row[0]))
                timestamps.append(float(row[1]))
    except Exception as e:
        print(f"Error reading file {file_path}: {e}")
        return None, None, None
    
    return np.array(frame_numbers, dtype=int), np.array(timestamps, dtype=float), header


def find_closest_timestamp_fast(target_timestamp, timestamps, frame_numbers, max_allowed_diff=10.0):
    """Use binary search to quickly find the closest timestamp (only works for sorted timestamps)"""
    if len(timestamps) == 0:
        return None, None
    
    # Binary search for insertion position (utilizing monotonic increasing property of timestamps)
    idx = np.searchsorted(timestamps, target_timestamp, side='left')
    
    # Candidate indices: idx-1 (less than or equal to target) and idx (greater than or equal to target)
    candidates = []
    if idx > 0:
        candidates.append(idx - 1)
    if idx < len(timestamps):
        candidates.append(idx)
    
    # Find index with minimum difference
    min_diff = float('inf')
    best_idx = -1
    timestamp = -1
    for i in candidates:
        diff = abs(timestamps[i] - target_timestamp)
        if diff < min_diff:
            min_diff = diff
            best_idx = i
            timestamp = timestamps[i]
    
    # Check if difference exceeds threshold
    if min_diff > max_allowed_diff:
        return None, None
    return frame_numbers[best_idx], timestamp


def _find_camera_video_path(current_dir, cam_num, video_name):
    """
    Find the camera video file matching "<video_name>.mp4" under Camera{cam_num}/
    """
    camera_dir = os.path.join(current_dir, f"Camera{cam_num}")
    if not os.path.isdir(camera_dir):
        return None

    target_suffix = f"{video_name}.mp4"
    for fn in os.listdir(camera_dir):
        if fn.endswith(target_suffix):
            return os.path.join(camera_dir, fn)
    return None


def _read_frame_rgb(video_path, frame_number):
    """
    Extract a single frame by absolute frame index.
    Returns RGB frame (H, W, 3) or None on failure.
    """
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        return None

    # Seek by frame index (works for most common codecs; if it fails, ret will be False)
    cap.set(cv2.CAP_PROP_POS_FRAMES, int(frame_number))
    ret, frame_bgr = cap.read()
    cap.release()

    if not ret or frame_bgr is None:
        return None
    return cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)


def _read_frames_rgb_accurate(
    video_path,
    frame_numbers,
    progress_desc=None,
    show_progress=True,
    tqdm_position=None,
):
    """
    Extract multiple frames by frame index using sequential decoding.

    This avoids inaccurate seeking (CAP_PROP_POS_FRAMES) for some codecs.
    """
    if not frame_numbers:
        return {}

    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        return {}

    wanted = sorted({int(fn) for fn in frame_numbers if fn is not None and int(fn) >= 0})
    if not wanted:
        cap.release()
        return {}

    wanted_set = set(wanted)
    max_target = wanted[-1]
    out = {}

    # Start from frame 0 then sequentially decode until max_target.
    cap.set(cv2.CAP_PROP_POS_FRAMES, 0)
    current_frame_idx = 0

    # Progress bar shows current decoded frame index.
    total_reads = max_target + 1
    pbar = None
    try:
        if show_progress:
            pbar = tqdm(
                total=total_reads,
                desc=progress_desc,
                unit="frame",
                leave=False,
                position=tqdm_position,
            )
        while current_frame_idx <= max_target:
            ret, frame_bgr = cap.read()
            if not ret or frame_bgr is None:
                break

            if current_frame_idx in wanted_set:
                out[current_frame_idx] = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)
                if len(out) == len(wanted):
                    # We already got all wanted frames.
                    # pbar will stop at current_frame_idx.
                    if pbar is not None:
                        pbar.update(1)
                    break

            if pbar is not None:
                pbar.update(1)
            current_frame_idx += 1
    finally:
        if pbar is not None:
            pbar.close()

    cap.release()
    return out


def save_sync_frames_montage(
    current_dir,
    sync_points,
    video_name,
    offsets=(-1,0,1),
    output_prefix=None,
    dpi=150,
    show_progress=True,
    preextract_multithread=True,
    preextract_max_workers=None,
    multithread_show_progress_per_cam=True,
):
    """
    Save user-provided sync frame images as a montage.

    For each offset in `offsets`, it creates a grid montage with one tile per camera:
      tile := frame at (sync_frame + offset)

    This produces one PNG per offset.
    """
    if output_prefix is None:
        output_prefix = f"sync_frames_montage_{video_name}"

    camera_list = sorted(sync_points.keys())
    num_cams = len(camera_list)
    if num_cams == 0:
        print("No sync_points provided; skip montage saving.")
        return

    cols = int(math.ceil(math.sqrt(num_cams)))
    rows = int(math.ceil(num_cams / cols))

    # Pre-resolve video paths to avoid repeated directory scans
    cam_video_paths = {}
    for cam_num in camera_list:
        cam_video_paths[cam_num] = _find_camera_video_path(current_dir, cam_num, video_name)
        if cam_video_paths[cam_num] is None:
            print(f"Warning: cannot find video for Camera{cam_num} (expects *{video_name}.mp4).")

    # Pre-extract all needed frames for each camera (t-2/t/t+2) accurately.
    # This matches the "opencv accurate" style in 3_extract_frames.py (sequential read).
    cam_frames_rgb = {}
    offsets = tuple(offsets)

    # Optionally parallelize pre-extraction per camera.
    # Each task opens its own VideoCapture and sequentially decodes until max_target.
    if preextract_multithread and len(camera_list) > 1:
        wanted_cams = [cam_num for cam_num in camera_list if cam_video_paths.get(cam_num) is not None]
        if not wanted_cams:
            return

        show_progress_for_cams = bool(show_progress) and bool(multithread_show_progress_per_cam)
        max_workers = preextract_max_workers if preextract_max_workers is not None else min(8, len(wanted_cams))

        with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as ex:
            future_to_cam = {}
            for pos, cam_num in enumerate(wanted_cams):
                video_path = cam_video_paths[cam_num]
                target_frames = [sync_points[cam_num] + off for off in offsets]
                future = ex.submit(
                    _read_frames_rgb_accurate,
                    video_path,
                    target_frames,
                    progress_desc=f"Reading Cam{cam_num} frames",
                    show_progress=show_progress_for_cams,
                    tqdm_position=pos if show_progress_for_cams else None,
                )
                future_to_cam[future] = cam_num

            # Progress over cameras (not per-frame) to avoid messy interleaved TQDM output.
            for fut in tqdm(concurrent.futures.as_completed(future_to_cam), total=len(future_to_cam), desc="Pre-extract cams", unit="cam"):
                cam_num = future_to_cam[fut]
                cam_frames_rgb[cam_num] = fut.result()
    else:
        for cam_num in camera_list:
            video_path = cam_video_paths.get(cam_num)
            if video_path is None:
                continue
            target_frames = [sync_points[cam_num] + off for off in offsets]
            cam_frames_rgb[cam_num] = _read_frames_rgb_accurate(
                video_path,
                target_frames,
                progress_desc=f"Reading Cam{cam_num} frames",
                show_progress=show_progress,
                tqdm_position=None,
            )

    # Create one montage per offset
    for off in offsets:
        fig, axes = plt.subplots(rows, cols, figsize=(cols * 4.2, rows * 3.2))
        axes = np.array(axes).reshape(rows, cols)

        # Turn off all axes first (handles when rows*cols > num_cams)
        for ax in axes.flat:
            ax.axis("off")

        any_rendered = False
        for i, cam_num in enumerate(camera_list):
            r, c = divmod(i, cols)
            ax = axes[r, c]

            base_frame = sync_points[cam_num]
            target_frame = base_frame + off

            frames_map = cam_frames_rgb.get(cam_num, {})
            frame_rgb = frames_map.get(target_frame)

            if not frame_rgb is None:
                any_rendered = True
                ax.imshow(frame_rgb)
                ax.set_title(f"Cam{cam_num}\nf{target_frame}", fontsize=9)
                ax.axis("off")
                continue

            video_path = cam_video_paths.get(cam_num)
            if video_path is None:
                ax.text(0.5, 0.5, f"Camera{cam_num}\nN/A", ha="center", va="center", fontsize=10)
                continue

            ax.text(
                0.5,
                0.5,
                f"Camera{cam_num}\nframe {target_frame}\nN/A",
                ha="center",
                va="center",
                fontsize=10,
            )

        fig.suptitle(f"Sync frames montage (video={video_name}, offset={off})", fontsize=12, fontweight="bold")
        plt.tight_layout()

        # Save montages under `<video_root>/sync_frames/`
        sync_frames_dir = os.path.join(current_dir, "sync_frames")
        os.makedirs(sync_frames_dir, exist_ok=True)

        output_image = os.path.join(sync_frames_dir, f"{output_prefix}_offset_{off}.png")
        if any_rendered:
            plt.savefig(output_image, dpi=dpi, bbox_inches="tight")
            print(f"Saved sync montage: {output_image}")
        else:
            print(f"Skipped saving {output_image} (no frames rendered).")

        plt.close(fig)


def process_with_sync_points(
    current_dir,
    sync_points,
    video_name,
    base_camera=1,
    draw_visualization=True,
    save_sync_frame_montage=True,
    sync_frame_offsets=(-1,0,1),
    sync_frame_montage_show_progress=True,
):
    """
    Synchronize frames across multiple videos based on known synchronization points
    
    This method reads timestamps (cap_msec, time difference relative to the first frame) 
    from preprocessed files, calculates time offsets from sync points, and uses 
    timestamp matching for synchronization.
    
    Args:
        current_dir: Root directory containing Camera folders and (optionally) a `csv/` folder
        sync_points: Dictionary with format {camera_num: sync_frame_num}
                    Example: {1: 1000, 2: 1050, 3: 980, 4: 1100, 5: 1020, 6: 1080}
                    Indicates that Camera1's frame 1000, Camera2's frame 1050, etc. are synchronized
        video_name: Video name (used for output filename)
        base_camera: Reference camera number (default: 1)
        draw_visualization: Whether to draw the dropped frames visualization (default: True)
    """
    video_root_dir = current_dir

    # Prefer `current_dir/csv/` for all intermediate CSV I/O.
    # If it doesn't exist, fall back to `current_dir` for backward compatibility.
    csv_dir = current_dir
    if os.path.basename(current_dir) != "csv":
        candidate = os.path.join(current_dir, "csv")
        if os.path.isdir(candidate):
            csv_dir = candidate

    all_files = os.listdir(csv_dir)
    print(f"Video root: {video_root_dir}")
    print(f"CSV directory: {csv_dir}")
    
    # Build CSV filename list
    csv_files = {}
    for cam_num in sync_points.keys():
        file_name = f'Camera{cam_num}_{video_name}_results.csv'
        if file_name in all_files:
            csv_files[cam_num] = file_name
        else:
            print(f"Warning: File not found {file_name}")
    
    if not csv_files:
        print("No CSV files found.")
        return
    
    if base_camera not in csv_files:
        print(f"Error: Reference camera {base_camera} file does not exist")
        return
    
    print(f"Selected Camera{base_camera} as reference camera")
    print(f"Synchronization point information:")
    for cam_num, sync_frame in sync_points.items():
        print(f"  Camera{cam_num}: Frame {sync_frame}")
    
    # Read data from all CSV files (including frame numbers and timestamps)
    data = {}
    headers = {}
    for cam_num, file_name in csv_files.items():
        file_path = os.path.join(csv_dir, file_name)
        frame_numbers, timestamps, header = read_csv_file(file_path)
        if frame_numbers is None:
            print(f"Skipping file {file_name}")
            continue
        data[cam_num] = (frame_numbers, timestamps)
        headers[cam_num] = header
    
    if base_camera not in data:
        print("Failed to read reference camera data")
        return
    
    # Read timestamps corresponding to sync points and calculate time offsets
    base_sync_frame = sync_points[base_camera]
    base_frames, base_timestamps_data = data[base_camera]
    
    # Find timestamp corresponding to reference camera sync frame
    base_sync_idx = np.where(base_frames == base_sync_frame)[0]
    if len(base_sync_idx) == 0:
        print(f"Error: Sync frame {base_sync_frame} not found in reference camera")
        return
    base_sync_ts = base_timestamps_data[base_sync_idx[0]]
    print(f"Reference camera sync frame {base_sync_frame} corresponds to timestamp: {base_sync_ts} ms")
    
    # Calculate time offset for each camera relative to reference (in milliseconds)
    time_offsets = {}
    time_offsets[base_camera] = 0.0
    
    for cam_num, sync_frame in sync_points.items():
        if cam_num == base_camera:
            continue
        
        frames, timestamps = data[cam_num]
        sync_idx = np.where(frames == sync_frame)[0]
        if len(sync_idx) == 0:
            print(f"Warning: Sync frame {sync_frame} not found in Camera{cam_num}, skipping")
            continue
        
        sync_ts = timestamps[sync_idx[0]]
        # Time offset = reference sync timestamp - current camera sync timestamp
        # If Camera2's sync frame timestamp is larger than reference, Camera2 is delayed, offset is negative
        time_offset = base_sync_ts - sync_ts
        time_offsets[cam_num] = time_offset
        print(f"  Camera{cam_num} sync frame {sync_frame} corresponds to timestamp: {sync_ts} ms")
        print(f"  Camera{cam_num} time offset relative to reference: {time_offset:.2f} ms")

    # Optional: save montage for user-provided sync frames (t-2, t, t+2).
    # This is independent from the timestamp-based matching result.
    if save_sync_frame_montage:
        save_sync_frames_montage(
            current_dir,
            sync_points,
            video_name,
            offsets=sync_frame_offsets,
            show_progress=sync_frame_montage_show_progress,
        )
    
    # Read reference file data
    base_frame_numbers, base_timestamps = data[base_camera]
    total_frames = len(base_frame_numbers)
    if total_frames == 0:
        print("Reference file has no data, exiting")
        return
    
    # Prepare output
    output_file = f'synchronized_frames_with_offset_{video_name}.csv'
    output_file = os.path.join(csv_dir, output_file)
    
    # Track which frames are used for each camera
    used_frames = {}
    for cam_num in csv_files.keys():
        used_frames[cam_num] = set()
    
    with open(output_file, 'w', newline='') as f:
        writer = csv.writer(f)
        # Build header
        header = [f'Camera{base_camera}']
        for cam_num in sorted(csv_files.keys()):
            if cam_num != base_camera:
                header.append(f"Camera{cam_num}")
        writer.writerow(header)
        
        successful_matches = 0
        
        # Process reference file row by row (using timestamp matching)
        for base_frame, base_ts in tqdm(
            zip(base_frame_numbers, base_timestamps),
            total=total_frames,
            desc="Processing progress"
        ):
            row = [base_frame]
            all_found = True
            
            for cam_num in sorted(csv_files.keys()):
                if cam_num == base_camera:
                    continue
                
                # Calculate target timestamp (reference timestamp - time offset)
                target_ts = base_ts - time_offsets.get(cam_num, 0.0)
                
                # Get current file's timestamps and frame numbers
                frames, timestamps = data[cam_num]
                
                # Quickly find closest timestamp
                closest_frame, ts = find_closest_timestamp_fast(
                    target_ts, timestamps, frames, max_allowed_diff=10.0
                )
                if closest_frame is None:
                    all_found = False
                    break
                row.append(closest_frame)
            
            # Only track frames as "used" if all cameras successfully matched
            if all_found:
                writer.writerow(row)
                successful_matches += 1
                # Track all frames in the row (only when successfully matched)
                # row[0] is base camera, row[1:] are other cameras in sorted order
                used_frames[base_camera].add(row[0])
                other_cameras = sorted([c for c in csv_files.keys() if c != base_camera])
                for idx, cam_num in enumerate(other_cameras):
                    if idx + 1 < len(row):
                        used_frames[cam_num].add(row[idx + 1])
        
        # Output matching results
        # Calculate total frames across all cameras
        total_frames_all_cameras = sum(len(frame_numbers) for frame_numbers, _ in data.values())
        # Calculate kept frames across all cameras (successful_matches * number of cameras)
        kept_frames_all_cameras = successful_matches * len(csv_files)
        match_ratio = kept_frames_all_cameras / total_frames_all_cameras if total_frames_all_cameras > 0 else 0
        print(f"Successfully matched frames: {kept_frames_all_cameras}/{total_frames_all_cameras} ({match_ratio:.2%})")
        print(f"  (Kept frames per camera: {successful_matches}, Total cameras: {len(csv_files)})")
    
    print(f"Synchronization results saved to {output_file}")
    
    # Find and visualize dropped frames
    if draw_visualization:
        visualize_dropped_frames(video_root_dir, data, used_frames, video_name, csv_files)
    save_dropped_frames_csv(csv_dir, data, used_frames, video_name, csv_files)


def visualize_dropped_frames(current_dir, data, used_frames, video_name, csv_files):
    """
    Visualize dropped frames for each camera
    
    Args:
        current_dir: Directory to save the output image
        data: Dictionary containing frame data for each camera {cam_num: (frame_numbers, timestamps)}
        used_frames: Dictionary containing used frame numbers for each camera {cam_num: set()}
        video_name: Video name (used for output filename)
        csv_files: Dictionary containing CSV filenames for each camera
    """
    # Calculate dropped frames and kept frames for each camera
    dropped_frames = {}
    kept_frames = {}
    max_frame = {}
    
    for cam_num in sorted(csv_files.keys()):
        if cam_num not in data:
            continue
        
        frame_numbers, _ = data[cam_num]
        used = used_frames.get(cam_num, set())
        all_frames = set(frame_numbers)
        dropped = sorted(list(all_frames - used))
        kept = sorted(list(used))
        dropped_frames[cam_num] = dropped
        kept_frames[cam_num] = kept
        max_frame[cam_num] = max(frame_numbers) if len(frame_numbers) > 0 else 0
    
    # Create visualization
    num_cameras = len(dropped_frames)
    if num_cameras == 0:
        print("No camera data to visualize")
        return
    
    fig, ax = plt.subplots(figsize=(16, max(6, num_cameras * 1.5)))
    
    # Bar height and spacing
    bar_height = 0.6
    spacing = 1.0
    y_positions = []
    
    # Draw rectangles for each camera
    camera_list = sorted(dropped_frames.keys())
    print("Drawing visualization...")
    for idx, cam_num in enumerate(camera_list):
        y_pos = idx * spacing
        y_positions.append(y_pos)
        
        max_f = max_frame[cam_num]
        total_frames = max_f + 1
        camera_name = f'Camera{cam_num}'
        
        # Draw the main rectangle (representing the entire video)
        # Rectangle width should match total frame count
        rect_width = total_frames
        rect = plt.Rectangle((0, y_pos - bar_height/2), rect_width, bar_height, 
                            facecolor='lightgray', edgecolor='black', linewidth=1.5)
        ax.add_patch(rect)
        
        # Draw white lines for kept frames (batch drawing for speed)
        kept = kept_frames[cam_num]
        if len(kept) > 0:
            # Convert to numpy array for faster processing
            kept_array = np.array(kept)
            y_bottom = y_pos - bar_height/2
            y_top = y_pos + bar_height/2
            # Use vlines for batch drawing (much faster than individual plot calls)
            ax.vlines(kept_array, y_bottom, y_top, colors='white', linewidths=0.01)
        
        # Draw red lines for dropped frames (batch drawing for speed)
        dropped = dropped_frames[cam_num]
        if len(dropped) > 0:
            # Convert to numpy array for faster processing
            dropped_array = np.array(dropped)
            y_bottom = y_pos - bar_height/2
            y_top = y_pos + bar_height/2
            # Use vlines for batch drawing (much faster than individual plot calls)
            ax.vlines(dropped_array, y_bottom, y_top, colors='red', linewidths=0.01)
        
        # Add frame count info
        dropped_count = len(dropped)
        kept_count = len(kept)
        info_text = f'Total: {total_frames}, Dropped: {dropped_count}, Kept: {kept_count}'
        ax.text(total_frames * 1.02, y_pos, info_text, ha='left', va='center', 
               fontsize=10)
    
    # Set axis properties
    max_total_frames = max([max_frame[cam] + 1 for cam in dropped_frames.keys()])
    ax.set_xlim(-max_total_frames * 0.1, max_total_frames * 1.15)
    ax.set_ylim(-0.5, (num_cameras - 1) * spacing + 0.5)
    ax.set_xlabel('Frame Number', fontsize=12, fontweight='bold')
    ax.set_ylabel('Camera', fontsize=12, fontweight='bold')
    ax.set_title(f'Dropped Frames Visualization (Video: {video_name})', 
                fontsize=14, fontweight='bold')
    ax.set_yticks(y_positions)
    ax.set_yticklabels([f'Camera{cam_num}' for cam_num in sorted(dropped_frames.keys())])
    ax.grid(True, alpha=0.3, axis='x')
    
    # Add legend
    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor='lightgray', edgecolor='black', label='Video Timeline'),
        plt.Line2D([0], [0], color='white', linewidth=0.01, label='Kept Frame'),
        plt.Line2D([0], [0], color='red', linewidth=0.01, label='Dropped Frame')
    ]
    ax.legend(handles=legend_elements, loc='upper right', fontsize=10)
    
    plt.tight_layout()
    
    # Save the figure
    output_image = f'dropped_frames_visualization_{video_name}.png'
    output_image = os.path.join(current_dir, output_image)
    plt.savefig(output_image, dpi=150, bbox_inches='tight')
    print(f"Dropped frames visualization saved to {output_image}")
    plt.close()


def save_dropped_frames_csv(current_dir, data, used_frames, video_name, csv_files):
    """
    Save dropped frame numbers to CSV file
    
    Args:
        current_dir: Directory to save the output CSV
        data: Dictionary containing frame data for each camera {cam_num: (frame_numbers, timestamps)}
        used_frames: Dictionary containing used frame numbers for each camera {cam_num: set()}
        video_name: Video name (used for output filename)
        csv_files: Dictionary containing CSV filenames for each camera
    """
    # Calculate dropped frames for each camera
    dropped_frames_dict = {}
    
    for cam_num in sorted(csv_files.keys()):
        if cam_num not in data:
            continue
        
        frame_numbers, _ = data[cam_num]
        used = used_frames.get(cam_num, set())
        all_frames = set(frame_numbers)
        dropped = sorted(list(all_frames - used))
        dropped_frames_dict[cam_num] = dropped
    
    # Find maximum number of dropped frames to determine CSV structure
    max_dropped = max([len(frames) for frames in dropped_frames_dict.values()]) if dropped_frames_dict else 0
    
    if max_dropped == 0:
        print("No dropped frames found")
        return
    
    # Prepare output CSV
    output_csv = f'dropped_frames_{video_name}.csv'
    output_csv = os.path.join(current_dir, output_csv)
    
    with open(output_csv, 'w', newline='') as f:
        writer = csv.writer(f)
        
        # Write header
        header = [f'Camera{cam_num}' for cam_num in sorted(dropped_frames_dict.keys())]
        writer.writerow(header)
        
        # Write dropped frames row by row
        for row_idx in range(max_dropped):
            row = []
            for cam_num in sorted(dropped_frames_dict.keys()):
                dropped = dropped_frames_dict[cam_num]
                if row_idx < len(dropped):
                    row.append(dropped[row_idx])
                else:
                    row.append('')  # Empty cell if no more dropped frames for this camera
            writer.writerow(row)
    
    print(f"Dropped frames CSV saved to {output_csv}")
    
    # Print summary
    print("\nDropped frames summary:")
    for cam_num in sorted(dropped_frames_dict.keys()):
        dropped = dropped_frames_dict[cam_num]
        if len(dropped) > 0:
            print(f"  Camera{cam_num}: {len(dropped)} frames dropped")
        else:
            print(f"  Camera{cam_num}: No frames dropped")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="Synchronize frames across cameras using timestamp offsets computed from user-provided sync points.",
    )
    parser.add_argument(
        "--dir",
        type=str,
        default=".",
        help="Directory containing Camera* folders and a csv/ folder (default: current directory).",
    )
    parser.add_argument(
        "--video-name",
        type=str,
        required=True,
        help="Video suffix, e.g. 0 for files ending with '*0.mp4' and CameraX_0_results.csv.",
    )
    parser.add_argument(
        "--sync-points",
        type=str,
        required=True,
        help="Sync points mapping like '1=315,2=298,3=287,4=292,5=297,6=289'.",
    )
    parser.add_argument("--base-camera", type=int, default=1)
    parser.add_argument("--no-visualization", action="store_true", help="Disable dropped-frame plot output.")
    args = parser.parse_args()

    def _parse_sync_points(s: str) -> dict[int, int]:
        out: dict[int, int] = {}
        for part in s.split(","):
            part = part.strip()
            if not part:
                continue
            if "=" not in part:
                raise ValueError(f"Invalid sync point '{part}', expected 'cam=frame'")
            cam, fr = part.split("=", 1)
            out[int(cam.strip())] = int(fr.strip())
        if not out:
            raise ValueError("sync_points is empty")
        return out

    current_dir = str(Path(args.dir).resolve())
    sync_points = _parse_sync_points(args.sync_points)
    draw_visualization = not args.no_visualization

    print("===== Frame Synchronization Tool (sync points) =====")
    process_with_sync_points(
        current_dir=current_dir,
        sync_points=sync_points,
        video_name=args.video_name,
        base_camera=args.base_camera,
        draw_visualization=draw_visualization,
    )