"""
Synchronized Frame Extractor

Usage:
    This script extracts synchronized frames from multiple camera videos based on 
    a synchronization CSV file. It allows you to specify a frame range (start_frame 
    to end_frame) from the reference camera video, and extracts the corresponding 
    synchronized frames from all cameras.

    The script:
    1. Reads a synchronization CSV file (generated by 2_sync_frames_finder.py)
    2. Finds CSV rows corresponding to the specified frame range (based on reference camera)
    3. Extracts frames from all camera videos using the synchronized frame numbers
    4. Saves extracted frames to organized folders (one folder per camera)

    Input CSV format (from 2_sync_frames_finder.py):
        Camera1,Camera2,Camera3,Camera4,Camera5,Camera6
        0,0,0,0,0,0
        1,1,1,1,1,1
        ...

    Frame Range Parameters:
        - start_frame: Starting frame number from reference camera video (0-based)
                       If None, starts from the beginning
        - end_frame: Ending frame number from reference camera video (inclusive)
                     If None, goes to the end
        - If both are None, extracts all synchronized frames

    Example:
        Modify the parameters in the __main__ section:
        - sync_csv_path: Path to synchronization CSV file
        - video_root: Root directory containing Camera folders (Camera1, Camera2, etc.)
        - start_frame: Starting frame number (e.g., 1000) or None
        - end_frame: Ending frame number (e.g., 2000) or None
        - video_name: Video file name (e.g., '0' for '0.mp4')
        - output_root: Output directory for extracted frames

    Output Structure:
        output_root/
        ├── Camera1/
        │   ├── row_00001_frame_0001000.jpg
        │   └── ...
        ├── Camera2/
        │   └── ...
        └── ...

    Extraction Methods:
        - 'opencv': Uses OpenCV (faster, accurate)
        - 'ffmpeg': Uses FFmpeg (most accurate, slower)

    Requirements:
        - opencv-python (cv2)
        - tqdm (for progress bars)
        - ffmpeg (optional, for ffmpeg extraction method)
"""

import cv2
import csv
import os
import subprocess
import threading
from tqdm import tqdm
import argparse
from pathlib import Path

def create_dir_if_not_exist(dir_path):
    """Create directory if it doesn't exist"""
    if not os.path.exists(dir_path):
        os.makedirs(dir_path)

def extract_frames_ffmpeg_individual(video_path, camera_name, frame_data_list, output_root, pbar):
    """
    Extract frames using ffmpeg individually (most accurate method)
    
    Args:
        frame_data_list: List of [(csv_row, frame_num), ...]
    """
    output_dir = os.path.join(output_root, camera_name)
    create_dir_if_not_exist(output_dir)
    
    for csv_row, frame_num in frame_data_list:
        # Output filename
        frame_filename = f"row_{csv_row:05d}_frame_{frame_num:07d}.jpg"
        frame_path = os.path.join(output_dir, frame_filename)
        
        # Use ffmpeg to extract single frame precisely
        cmd = [
            'ffmpeg', '-y', '-loglevel', 'error',
            '-i', video_path,
            '-vf', f"select='eq(n\\,{frame_num})'",
            '-frames:v', '1',
            '-update', '1',
            frame_path
        ]
        
        try:
            subprocess.run(cmd, check=True, capture_output=True, timeout=30)
        except subprocess.TimeoutExpired:
            print(f"⚠️  Camera {camera_name} frame {frame_num} (CSV row {csv_row}) extraction timeout")
        except subprocess.CalledProcessError:
            # Silent failure, continue to next frame
            pass
        
        pbar.update(1)

def extract_frames_opencv_accurate(video_path, camera_name, frame_data_list, output_root, pbar):
    """
    Extract frames using OpenCV accurately (accurate version: read frame by frame, 
    periodically reopen video for performance optimization).

    If the sync CSV lists the same frame number multiple times for this camera (sorted order
    will place them consecutively), the **same decoded image** is written to each output path
    without re-seeking or re-reading from the beginning of the file. This avoids catastrophic
    slowdown from ``target_frame_num < current_frame_idx`` reopen logic.

    Args:
        frame_data_list: List of [(csv_row, frame_num), ...], sorted by frame number
    """
    output_dir = os.path.join(output_root, camera_name)
    create_dir_if_not_exist(output_dir)

    # Sort by frame number for sequential reading
    sorted_frames = sorted(frame_data_list, key=lambda x: x[1])

    current_frame_idx = 0  # Current video position (index of *next* frame to read)
    cap = None
    frames_processed_since_reopen = 0
    reopen_interval = 5000  # Reopen video every 5000 frames (performance optimization)

    # Last successfully decoded frame (same frame index may repeat in CSV)
    last_frame_num = None
    last_frame = None

    for csv_row, target_frame_num in sorted_frames:
        # Duplicate frame index: reuse pixels, do not advance VideoCapture (no rewind from 0)
        if last_frame is not None and target_frame_num == last_frame_num:
            frame_filename = f"row_{csv_row:05d}_frame_{target_frame_num:07d}.jpg"
            frame_path = os.path.join(output_dir, frame_filename)
            cv2.imwrite(frame_path, last_frame)
            pbar.update(1)
            continue

        # Reopen video if need to start from beginning, or processed many frames (performance optimization)
        if (target_frame_num < current_frame_idx or
                frames_processed_since_reopen >= reopen_interval or
                cap is None):
            if cap is not None:
                cap.release()
            cap = cv2.VideoCapture(video_path)
            if not cap.isOpened():
                print(f"❌ Cannot open video: {video_path}")
                pbar.update(len(frame_data_list) - sorted_frames.index((csv_row, target_frame_num)))
                return
            cap.set(cv2.CAP_PROP_POS_FRAMES, 0)
            current_frame_idx = 0
            frames_processed_since_reopen = 0
            last_frame_num = None
            last_frame = None

        # Read frame by frame from current position to target frame (ensure accuracy)
        while current_frame_idx < target_frame_num:
            ret, _ = cap.read()
            if not ret:
                print(f"⚠️  Camera {camera_name} frame {target_frame_num} (CSV row {csv_row}) exceeds video range")
                pbar.update(1)
                return
            current_frame_idx += 1

        # Now current_frame_idx should equal target_frame_num, read target frame
        ret, frame = cap.read()
        if ret:
            frame_filename = f"row_{csv_row:05d}_frame_{target_frame_num:07d}.jpg"
            frame_path = os.path.join(output_dir, frame_filename)
            cv2.imwrite(frame_path, frame)
            last_frame_num = target_frame_num
            last_frame = frame.copy()
            current_frame_idx += 1
            frames_processed_since_reopen += 1
        else:
            print(f"⚠️  Camera {camera_name} frame {target_frame_num} (CSV row {csv_row}) read failed")

        pbar.update(1)

    if cap is not None:
        cap.release()

def extract_synced_frames(sync_csv_path, video_root, output_root, start_frame, end_frame, video_name, base_camera=1):
    """
    Extract synchronized frames from specified frame range based on synchronization CSV
    
    Args:
        sync_csv_path: Path to synchronization CSV file
        video_root: Root directory containing Camera folders
        output_root: Output root directory for extracted frames
        start_frame: Starting frame number from reference camera video (0-based, None = from beginning)
        end_frame: Ending frame number from reference camera video (inclusive, None = to end)
        video_name: Video file name (e.g., '0' for '0.mp4')
        base_camera: Reference camera number (default: 1, used to determine frame range)
    """
    # 1. Read synchronization CSV and find rows corresponding to frame range
    sync_frame_map = {}  # key: camera name, value: list of target frame numbers
    camera_names = []    # Store camera order (consistent with CSV columns)
    csv_rows_data = []   # Store all CSV rows with their indices

    with open(sync_csv_path, 'r', newline='') as f:
        reader = csv.reader(f)
        header = next(reader)  # First row contains camera names (Camera1, Camera2...)
        camera_names = header

        # Initialize frame number list for each camera
        for cam in camera_names:
            sync_frame_map[cam] = []

        # Read all data rows and store them
        row_idx = 0
        for row in reader:
            row_idx += 1
            frame_numbers = [int(row[cam_idx]) for cam_idx in range(len(camera_names))]
            csv_rows_data.append((row_idx, frame_numbers))  # (CSV row index, list of frame numbers)

    # Find reference camera index
    base_camera_name = f'Camera{base_camera}'
    if base_camera_name not in camera_names:
        print(f"❌ Reference camera {base_camera_name} not found in CSV header")
        return
    
    base_camera_idx = camera_names.index(base_camera_name)
    
    # Filter CSV rows based on frame range (using reference camera frame numbers)
    filtered_rows = []
    for csv_row_idx, frame_numbers in csv_rows_data:
        ref_frame_num = frame_numbers[base_camera_idx]
        
        # Check if this row is within the specified frame range
        if start_frame is not None and ref_frame_num < start_frame:
            continue
        if end_frame is not None and ref_frame_num > end_frame:
            continue
        
        filtered_rows.append((csv_row_idx, frame_numbers))
    
    # Store filtered frame data for each camera
    for csv_row_idx, frame_numbers in filtered_rows:
        for cam_idx, cam_name in enumerate(camera_names):
            frame_num = frame_numbers[cam_idx]
            sync_frame_map[cam_name].append((csv_row_idx, frame_num))  # (CSV row number, frame number)

    # Validate target frame count (all cameras should have the same number of frames)
    target_frame_count = len(sync_frame_map[camera_names[0]]) if camera_names else 0
    
    # Format output information
    if start_frame is None and end_frame is None:
        frame_range_str = "all frames (from start to end)"
    elif start_frame is None:
        frame_range_str = f"frames 0-{end_frame}"
    elif end_frame is None:
        frame_range_str = f"frames {start_frame} to end"
    else:
        frame_range_str = f"frames {start_frame}-{end_frame}"
    
    print(f"📊 Target extraction: {target_frame_count} synchronized frame groups (CSV {frame_range_str} from {base_camera_name})")
    print(f"📹 Cameras involved: {camera_names}")
    
    # Check for duplicate frame numbers (may cause file overwriting)
    print(f"\n🔍 Checking for duplicate frame numbers in CSV:")
    for cam_name in camera_names:
        frame_data_list = sync_frame_map[cam_name]
        frame_numbers = [fn for _, fn in frame_data_list]
        unique_count = len(set(frame_numbers))
        if len(frame_numbers) != unique_count:
            duplicates = len(frame_numbers) - unique_count
            print(f"  ⚠️  {cam_name}: {duplicates} duplicate frame numbers (total {len(frame_numbers)}, unique {unique_count})")
        else:
            print(f"  ✅ {cam_name}: No duplicate frame numbers")

    if target_frame_count == 0:
        print("❌ No target frames found (frame range may be outside CSV data range)")
        return

    # 2. Prepare video paths (assumes video path: video_root/CameraX/{video_name}.mp4)
    video_paths = {}
    for cam_name in camera_names:
        video_path = os.path.join(video_root, cam_name, f"{video_name}.mp4")
        if not os.path.exists(video_path):
            print(f"❌ Video file not found: {video_path}")
            return
        video_paths[cam_name] = video_path

    # 3. Choose extraction method
    # Method options: 'ffmpeg' = use ffmpeg individual extraction (most accurate, slower)
    #                 'opencv' = use improved OpenCV method (read frame by frame from current position, accurate and faster)
    extract_method = 'opencv'  # Can be changed to 'ffmpeg' if highest accuracy is needed
    
    print(f"\n🔧 Extraction method: {extract_method}")
    if extract_method == 'ffmpeg':
        print("   (ffmpeg individual extraction - most accurate but slower)")
    else:
        print("   (OpenCV frame-by-frame reading - accurate and faster)")
    
    # 4. Multi-threaded frame extraction (one thread per camera)
    threads = []
    total_tasks = target_frame_count * len(camera_names)
    pbar = tqdm(total=total_tasks, desc="📸 Extraction progress", unit="frame")

    for cam_name in camera_names:
        frame_data_list = sync_frame_map[cam_name]
        video_path = video_paths[cam_name]
        
        # Call different function based on selected method
        if extract_method == 'ffmpeg':
            extract_func = extract_frames_ffmpeg_individual
            args = (video_path, cam_name, frame_data_list, output_root, pbar)
        else:
            extract_func = extract_frames_opencv_accurate
            args = (video_path, cam_name, frame_data_list, output_root, pbar)
        
        # Create thread
        thread = threading.Thread(
            target=extract_func,
            args=args,
            name=f"Thread-{cam_name}"
        )
        threads.append(thread)
        thread.start()

    # Wait for all threads to complete
    for thread in threads:
        thread.join()
    pbar.close()

    print(f"\n✅ Frame extraction completed! All synchronized frames saved to: {output_root}")
    print(f"📋 Statistics: Extracted {target_frame_count} synchronized frame groups, involving {len(camera_names)} cameras")
    
    # Count files in all output folders
    print(f"\n📁 File count statistics for each folder:")
    if os.path.exists(output_root):
        # Get all subdirectories and sort
        subdirs = sorted([d for d in os.listdir(output_root) 
                         if os.path.isdir(os.path.join(output_root, d))])
        if subdirs:
            for subdir in subdirs:
                subdir_path = os.path.join(output_root, subdir)
                file_count = len([f for f in os.listdir(subdir_path) 
                                 if os.path.isfile(os.path.join(subdir_path, f))])
                print(f"  {subdir}: {file_count} files")
        else:
            print(f"  ⚠️  No subdirectories found in output directory")
    else:
        print(f"  ⚠️  Output directory does not exist: {output_root}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Extract synchronized frames from Camera* videos using a sync CSV.",
    )
    parser.add_argument(
        "--video-root",
        type=str,
        default=".",
        help="Root directory containing Camera* folders and csv/ (default: current directory).",
    )
    parser.add_argument(
        "--video-name",
        type=str,
        required=True,
        help="Video suffix, e.g. 0 for CameraX/0.mp4 and synchronized_frames_with_offset_0.csv",
    )
    parser.add_argument(
        "--sync-csv",
        type=str,
        default=None,
        help="Path to synchronized_frames_with_offset_<video>.csv (default: auto-detect under video-root/csv or video-root).",
    )
    parser.add_argument("--start-frame", type=int, default=None)
    parser.add_argument("--end-frame", type=int, default=None)
    parser.add_argument(
        "--output-root",
        type=str,
        default=None,
        help="Output directory (default: <video-root>/frames/<video>.mp4/<range>).",
    )
    parser.add_argument("--base-camera", type=int, default=1)
    args = parser.parse_args()

    video_root = str(Path(args.video_root).resolve())
    video_name = args.video_name

    if args.sync_csv is None:
        candidate = os.path.join(video_root, "csv", f"synchronized_frames_with_offset_{video_name}.csv")
        legacy = os.path.join(video_root, f"synchronized_frames_with_offset_{video_name}.csv")
        sync_csv_path = candidate if os.path.exists(candidate) else legacy
    else:
        sync_csv_path = str(Path(args.sync_csv).resolve())

    start_frame = args.start_frame
    end_frame = args.end_frame

    if args.output_root is None:
        if start_frame is None and end_frame is None:
            range_dir = "all"
        elif start_frame is None:
            range_dir = f"start_{end_frame}"
        elif end_frame is None:
            range_dir = f"{start_frame}_end"
        else:
            range_dir = f"{start_frame}_{end_frame}"
        output_root = os.path.join(video_root, "frames", f"{video_name}.mp4", range_dir)
    else:
        output_root = str(Path(args.output_root).resolve())

    extract_synced_frames(
        sync_csv_path=sync_csv_path,
        video_root=video_root,
        output_root=output_root,
        start_frame=start_frame,
        end_frame=end_frame,
        video_name=video_name,
        base_camera=args.base_camera,
    )
